"""update table case

Revision ID: 0b9e86f5cd03
Revises: cbd009df8ad6
Create Date: 2022-05-26 15:53:58.030367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9e86f5cd03'
down_revision = 'cbd009df8ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('creator', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'creator')
    # ### end Alembic commands ###
