"""Initial migration.

Revision ID: 52559ee8882e
Revises: 
Create Date: 2022-05-11 22:24:23.754244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52559ee8882e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('ba', sa.Boolean(), nullable=True),
    sa.Column('dev', sa.Boolean(), nullable=True),
    sa.Column('qa', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sprint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.Date(), nullable=True),
    sa.Column('end_time', sa.Date(), nullable=True),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.Column('story_cards', sa.Integer(), nullable=True),
    sa.Column('spike_cards', sa.Integer(), nullable=True),
    sa.Column('bug_cards', sa.Integer(), nullable=True),
    sa.Column('task_cards', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('ac', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Date(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('sprint', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['sprint'], ['sprint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bug',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bug', sa.String(length=500), nullable=True),
    sa.Column('card', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('tester', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardMemberRelationship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card', sa.Integer(), nullable=True),
    sa.Column('member', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card'], ['card.id'], ),
    sa.ForeignKeyConstraint(['member'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardStateChangeLog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card', sa.Integer(), nullable=True),
    sa.Column('prev', sa.String(length=50), nullable=True),
    sa.Column('current', sa.String(length=50), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['card'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case', sa.String(length=500), nullable=True),
    sa.Column('card', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('auto', sa.Boolean(), nullable=True),
    sa.Column('effect', sa.String(length=50), nullable=True),
    sa.Column('creator', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risk', sa.String(length=500), nullable=True),
    sa.Column('card', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=500), nullable=True),
    sa.Column('card', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('risk')
    op.drop_table('case')
    op.drop_table('cardStateChangeLog')
    op.drop_table('cardMemberRelationship')
    op.drop_table('bug')
    op.drop_table('card')
    op.drop_table('sprint')
    op.drop_table('member')
    # ### end Alembic commands ###
