"""update card associated table.

Revision ID: 623566e1e80a
Revises: 6335c10768b8
Create Date: 2022-08-30 16:32:13.967709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623566e1e80a'
down_revision = '6335c10768b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cardrelatedcard_ibfk_2', 'cardRelatedCard', type_='foreignkey')
    op.drop_constraint('cardrelatedcard_ibfk_1', 'cardRelatedCard', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('cardrelatedcard_ibfk_1', 'cardRelatedCard', 'card', ['card1'], ['id'])
    op.create_foreign_key('cardrelatedcard_ibfk_2', 'cardRelatedCard', 'card', ['card2'], ['id'])
    # ### end Alembic commands ###
