"""update fields in card associated table.

Revision ID: 6335c10768b8
Revises: cc330a7b098e
Create Date: 2022-08-30 16:15:14.026532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6335c10768b8'
down_revision = 'cc330a7b098e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardRelatedCard', sa.Column('card1', sa.Integer(), nullable=True))
    op.add_column('cardRelatedCard', sa.Column('card2', sa.Integer(), nullable=True))
    op.add_column('cardRelatedCard', sa.Column('operator', sa.String(length=50), nullable=True))
    op.drop_constraint('cardrelatedcard_ibfk_1', 'cardRelatedCard', type_='foreignkey')
    op.drop_constraint('cardrelatedcard_ibfk_2', 'cardRelatedCard', type_='foreignkey')
    op.create_foreign_key(None, 'cardRelatedCard', 'card', ['card1'], ['id'])
    op.create_foreign_key(None, 'cardRelatedCard', 'card', ['card2'], ['id'])
    op.drop_column('cardRelatedCard', 'state')
    op.drop_column('cardRelatedCard', 'case')
    op.drop_column('cardRelatedCard', 'card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardRelatedCard', sa.Column('card', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cardRelatedCard', sa.Column('case', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cardRelatedCard', sa.Column('state', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'cardRelatedCard', type_='foreignkey')
    op.drop_constraint(None, 'cardRelatedCard', type_='foreignkey')
    op.create_foreign_key('cardrelatedcard_ibfk_2', 'cardRelatedCard', 'case', ['case'], ['id'])
    op.create_foreign_key('cardrelatedcard_ibfk_1', 'cardRelatedCard', 'card', ['card'], ['id'])
    op.drop_column('cardRelatedCard', 'operator')
    op.drop_column('cardRelatedCard', 'card2')
    op.drop_column('cardRelatedCard', 'card1')
    # ### end Alembic commands ###
