"""delete bug table.

Revision ID: 666db36826f4
Revises: 78afe784e557
Create Date: 2022-09-08 16:54:21.875076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '666db36826f4'
down_revision = '78afe784e557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bug', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('card', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('level', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('owner', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tester', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['card'], ['card.id'], name='bug_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
