"""update membership table.

Revision ID: 78afe784e557
Revises: b89acc4c4679
Create Date: 2022-09-07 17:44:46.011450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78afe784e557'
down_revision = 'b89acc4c4679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardMemberRelationship', sa.Column('member_pair', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cardMemberRelationship', 'member', ['member_pair'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cardMemberRelationship', type_='foreignkey')
    op.drop_column('cardMemberRelationship', 'member_pair')
    # ### end Alembic commands ###
