"""delte table: tag

Revision ID: 9e295db15071
Revises: cd564580fb46
Create Date: 2022-06-09 21:59:50.113116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e295db15071'
down_revision = 'cd564580fb46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.add_column('case', sa.Column('tag', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'tag')
    op.create_table('tag',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tag', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('case', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case'], ['case.id'], name='tag_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
