"""update card associated table.

Revision ID: b89acc4c4679
Revises: 623566e1e80a
Create Date: 2022-08-30 16:36:17.177600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89acc4c4679'
down_revision = '623566e1e80a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cardRelatedCard', 'card', ['card2'], ['id'])
    op.create_foreign_key(None, 'cardRelatedCard', 'card', ['card1'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cardRelatedCard', type_='foreignkey')
    op.drop_constraint(None, 'cardRelatedCard', type_='foreignkey')
    # ### end Alembic commands ###
