"""update project table

Revision ID: c9441f88d503
Revises: ed1e65eaeb4d
Create Date: 2022-06-22 19:33:41.912650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9441f88d503'
down_revision = 'ed1e65eaeb4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('create_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'create_at')
    # ### end Alembic commands ###
