"""add case related content. such as:case.

Revision ID: cbd009df8ad6
Revises: 52559ee8882e
Create Date: 2022-05-26 10:51:58.849080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbd009df8ad6'
down_revision = '52559ee8882e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caseRelatedCard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case', sa.Integer(), nullable=True),
    sa.Column('card', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card'], ['card.id'], ),
    sa.ForeignKeyConstraint(['case'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('case', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('case', sa.Column('module', sa.String(length=100), nullable=True))
    op.add_column('case', sa.Column('review', sa.String(length=50), nullable=True))
    op.add_column('case', sa.Column('given', sa.String(length=500), nullable=True))
    op.add_column('case', sa.Column('when', sa.String(length=500), nullable=True))
    op.add_column('case', sa.Column('then', sa.String(length=500), nullable=True))
    op.add_column('case', sa.Column('result', sa.String(length=50), nullable=True))
    op.drop_constraint('case_ibfk_1', 'case', type_='foreignkey')
    op.drop_column('case', 'case')
    op.drop_column('case', 'state')
    op.drop_column('case', 'creator')
    op.drop_column('case', 'card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('card', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('case', sa.Column('creator', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('case', sa.Column('state', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('case', sa.Column('case', mysql.VARCHAR(length=500), nullable=True))
    op.create_foreign_key('case_ibfk_1', 'case', 'card', ['card'], ['id'])
    op.drop_column('case', 'result')
    op.drop_column('case', 'then')
    op.drop_column('case', 'when')
    op.drop_column('case', 'given')
    op.drop_column('case', 'review')
    op.drop_column('case', 'module')
    op.drop_column('case', 'name')
    op.drop_table('caseRelatedCard')
    # ### end Alembic commands ###
