"""add table: tag

Revision ID: cd564580fb46
Revises: 0b9e86f5cd03
Create Date: 2022-06-09 21:54:43.175300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd564580fb46'
down_revision = '0b9e86f5cd03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('case', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('case', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('tag', mysql.VARCHAR(length=50), nullable=True))
    op.drop_table('tag')
    # ### end Alembic commands ###
