"""add project table

Revision ID: ed1e65eaeb4d
Revises: 9e295db15071
Create Date: 2022-06-22 19:21:26.411745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed1e65eaeb4d'
down_revision = '9e295db15071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('robot', sa.String(length=500), nullable=True),
    sa.Column('points_data', sa.Boolean(), nullable=True),
    sa.Column('cards_data', sa.Boolean(), nullable=True),
    sa.Column('burn_down_chart', sa.Boolean(), nullable=True),
    sa.Column('cumulative_flow_chart', sa.Boolean(), nullable=True),
    sa.Column('point_overflow_rate_data', sa.Boolean(), nullable=True),
    sa.Column('commitment_fulfillment_rate_data', sa.Boolean(), nullable=True),
    sa.Column('good_card_rate_data', sa.Boolean(), nullable=True),
    sa.Column('average_test_costs_data', sa.Boolean(), nullable=True),
    sa.Column('bug_data', sa.Boolean(), nullable=True),
    sa.Column('left_bug_data', sa.Boolean(), nullable=True),
    sa.Column('test_coverage_data', sa.Boolean(), nullable=True),
    sa.Column('regression_test_data', sa.Boolean(), nullable=True),
    sa.Column('points_spent_per_card_chart', sa.Boolean(), nullable=True),
    sa.Column('percentage_of_points_delivered_chart', sa.Boolean(), nullable=True),
    sa.Column('trend_different_type_cards_chart', sa.Boolean(), nullable=True),
    sa.Column('trend_completion_points_chart', sa.Boolean(), nullable=True),
    sa.Column('trend_completion_cards_chart', sa.Boolean(), nullable=True),
    sa.Column('trend_bug_created_chart', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
